import {
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  BookOpen,
  Check,
  ChevronRight,
  Code2,
  Download,
  Flame,
  Flower2,
  Globe,
  HelpCircle,
  Leaf,
  Lightbulb,
  Menu,
  Play,
  RotateCcw,
  Settings,
  ShieldCheck,
  Sparkles,
  Sprout,
  Terminal,
  Trophy,
  Volume2,
  X,
  Zap,
  Search,
  Undo2,
  LockKeyhole,
  ExternalLink,
  Home,
  CheckCheck,
  CircleCheck,
  Circle,
} from 'lucide-react';
const icons = {
  arrow: ArrowRight,
  left: ArrowLeft,
  up: ArrowUp,
  down: ArrowDown,
  book: BookOpen,
  check: Check,
  chevron: ChevronRight,
  code: Code2,
  download: Download,
  flame: Flame,
  flower: Flower2,
  globe: Globe,
  help: HelpCircle,
  leaf: Leaf,
  hint: Lightbulb,
  menu: Menu,
  play: Play,
  reset: RotateCcw,
  settings: Settings,
  shield: ShieldCheck,
  sparkle: Sparkles,
  sprout: Sprout,
  terminal: Terminal,
  trophy: Trophy,
  volume: Volume2,
  close: X,
  zap: Zap,
  search: Search,
  undo: Undo2,
  lock: LockKeyhole,
  external: ExternalLink,
  home: Home,
  checks: CheckCheck,
  complete: CircleCheck,
  circle: Circle,
};
export type IconName = keyof typeof icons;
export function Icon({
  name,
  size = 20,
  className = '',
}: {
  name: IconName;
  size?: number;
  className?: string;
}) {
  const Component = icons[name];
  return <Component size={size} strokeWidth={1.8} className={className} aria-hidden="true" />;
}
