import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root = path.resolve(import.meta.dirname, '..');
const dist = path.join(root, 'dist');
const docs = path.join(root, 'docs');
if (!fs.existsSync(path.join(dist, 'index.html'))) throw Error('Build the app before staging.');
// Both targets are fixed children of this checkout, never caller-supplied paths.
if (path.dirname(docs) !== root || path.basename(docs) !== 'docs')
  throw Error('Invalid staging directory');
fs.mkdirSync(docs, { recursive: true });
for (const file of fs.readdirSync(docs))
  fs.rmSync(path.join(docs, file), { recursive: true, force: true });
fs.cpSync(dist, docs, { recursive: true });
function walk(dir, prefix = '') {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) =>
      entry.isDirectory()
        ? walk(path.join(dir, entry.name), prefix + entry.name + '/')
        : ['./' + prefix + entry.name]
    );
}
const files = walk(docs).sort();
const hash = crypto.createHash('sha256');
for (const file of files) hash.update(fs.readFileSync(path.join(docs, file.slice(2))));
const revision = hash.digest('hex').slice(0, 12);
const worker = `// CodeSprout offline shell. Generated by scripts/stage.mjs.
const CACHE = 'codesprout-${revision}';
const FILES = ${JSON.stringify(files)};
const ROOT = new URL('./',self.location.href);
const ALLOWED = new Set(FILES.map(file=>new URL(file,ROOT).href));
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(FILES))));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('codesprout-')&&key!==CACHE)await caches.delete(key);await self.clients.claim();})()));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==ROOT.origin||!url.pathname.startsWith(ROOT.pathname))return;
 if(event.request.mode==='navigate'){
  event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(new URL('./index.html',ROOT).href))||fetch(event.request)));
 }else if(ALLOWED.has(url.href)){
  event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(event.request))||fetch(event.request)));
 }
});
`;
fs.writeFileSync(path.join(docs, 'sw.js'), worker);
fs.writeFileSync(
  path.join(docs, 'version.json'),
  JSON.stringify({
    version: JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version,
    revision,
  })
);
fs.writeFileSync(path.join(docs, '.nojekyll'), '');
console.log(`Staged ${files.length} offline assets; release ${revision}`);
